/*
Copyright 2019-2023 TensorChord Inc.

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/tensorchord/openmodelz/modelzetes/pkg/apis/modelzetes/v2alpha1"
	scheme "github.com/tensorchord/openmodelz/modelzetes/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// InferencesGetter has a method to return a InferenceInterface.
// A group's client should implement this interface.
type InferencesGetter interface {
	Inferences(namespace string) InferenceInterface
}

// InferenceInterface has methods to work with Inference resources.
type InferenceInterface interface {
	Create(ctx context.Context, inference *v2alpha1.Inference, opts v1.CreateOptions) (*v2alpha1.Inference, error)
	Update(ctx context.Context, inference *v2alpha1.Inference, opts v1.UpdateOptions) (*v2alpha1.Inference, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.Inference, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.InferenceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.Inference, err error)
	InferenceExpansion
}

// inferences implements InferenceInterface
type inferences struct {
	client rest.Interface
	ns     string
}

// newInferences returns a Inferences
func newInferences(c *TensorchordV2alpha1Client, namespace string) *inferences {
	return &inferences{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the inference, and returns the corresponding inference object, and an error if there is any.
func (c *inferences) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.Inference, err error) {
	result = &v2alpha1.Inference{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inferences").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Inferences that match those selectors.
func (c *inferences) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.InferenceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.InferenceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("inferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested inferences.
func (c *inferences) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("inferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a inference and creates it.  Returns the server's representation of the inference, and an error, if there is any.
func (c *inferences) Create(ctx context.Context, inference *v2alpha1.Inference, opts v1.CreateOptions) (result *v2alpha1.Inference, err error) {
	result = &v2alpha1.Inference{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("inferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inference).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a inference and updates it. Returns the server's representation of the inference, and an error, if there is any.
func (c *inferences) Update(ctx context.Context, inference *v2alpha1.Inference, opts v1.UpdateOptions) (result *v2alpha1.Inference, err error) {
	result = &v2alpha1.Inference{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("inferences").
		Name(inference.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(inference).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the inference and deletes it. Returns an error if one occurs.
func (c *inferences) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inferences").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *inferences) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("inferences").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched inference.
func (c *inferences) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.Inference, err error) {
	result = &v2alpha1.Inference{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("inferences").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
