# Default values for openmodelz.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

createCRDs: true              # Set to false if applying CRDs in another way

imagePullPolicy: "Always"

rbac: true                    # Kubernetes RBAC, no good reason to disable this

basicAuth: false              # Authentication for core components
generateBasicAuth: false      # Set to false if applying credentials separately from the chart, otherwise set to true

clusterRole: true            # Set to true for multiple namespaces.

httpProbe: true              # Setting to true will use HTTP for readiness and liveness probe on function pods

exposeServices: true
serviceType: NodePort        # serviceType for agent.

securityContext: true

debug: true

privatedImage: false
dockerconfigjson: ""
imagePullSecret: ""

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

nodeSelector: {}

tolerations: []

affinity: {}

autoscaler:
  image: modelzai/openmodelz-autoscaler:v0.0.6
  replicas: 1
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "2Gi"
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

priorityClass:
  modelz: "modelz"
  modelzValue: 10000000
  inference: "inference"
  inferenceValue: 1000000

ingressOperator:
  image: modelzai/openmodelz-ingress-operator:v0.0.6
  replicas: 1
  create: true
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      cpu: "500m"
      memory: "2Gi"

modelzetes:
  image: modelzai/openmodelz-modelzetes:v0.0.6
  resources:
    requests:
      memory: "120Mi"
      cpu: "100m"
    limits:
      cpu: "1000m"
      memory: "3Gi"
  imagePullPolicy: "IfNotPresent"    # Image pull policy for deployed inferences
  httpProbe: true              # Setting to true will use HTTP for readiness and liveness probe on function pods
  readinessProbe:
    initialDelaySeconds: 2
    timeoutSeconds: 1           # Tuned-in to run checks early and quickly to support fast cold-start from zero replicas
    periodSeconds: 1            # Reduce to 1 for a faster cold-start, increase higher for lower-CPU usage
  livenessProbe:
    initialDelaySeconds: 2
    timeoutSeconds: 1
    periodSeconds: 1           # Reduce to 1 for a faster cold-start, increase higher for lower-CPU usage
  startupProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 2
  huggingfacePullThroughCache:
    enabled: false

agent:
  image: modelzai/openmodelz-agent:v0.0.6
  readTimeout: "305s"
  writeTimeout: "305s"
  replicas: 1
  # change the port when creating multiple releases in the same baremetal cluster
  nodePort: 31112

  resources:
    requests:
      memory: "120Mi"
      cpu: "100m"
    limits:
      cpu: "2"
      memory: "8Gi"

  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  livenessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

# monitoring and auto-scaling components
# both components
prometheus:
  image: prom/prometheus:v2.41.0
  create: true
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "3Gi"
  annotations: {}
