/*
Copyright 2023 TensorChord Inc.

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// InferenceIngressListerExpansion allows custom methods to be added to
// InferenceIngressLister.
type InferenceIngressListerExpansion interface{}

// InferenceIngressNamespaceListerExpansion allows custom methods to be added to
// InferenceIngressNamespaceLister.
type InferenceIngressNamespaceListerExpansion interface{}
