/*
Copyright 2019-2023 TensorChord Inc.

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2alpha1 "github.com/tensorchord/openmodelz/modelzetes/pkg/apis/modelzetes/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInferences implements InferenceInterface
type FakeInferences struct {
	Fake *FakeTensorchordV2alpha1
	ns   string
}

var inferencesResource = schema.GroupVersionResource{Group: "tensorchord.ai", Version: "v2alpha1", Resource: "inferences"}

var inferencesKind = schema.GroupVersionKind{Group: "tensorchord.ai", Version: "v2alpha1", Kind: "Inference"}

// Get takes name of the inference, and returns the corresponding inference object, and an error if there is any.
func (c *FakeInferences) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.Inference, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(inferencesResource, c.ns, name), &v2alpha1.Inference{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.Inference), err
}

// List takes label and field selectors, and returns the list of Inferences that match those selectors.
func (c *FakeInferences) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.InferenceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(inferencesResource, inferencesKind, c.ns, opts), &v2alpha1.InferenceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2alpha1.InferenceList{ListMeta: obj.(*v2alpha1.InferenceList).ListMeta}
	for _, item := range obj.(*v2alpha1.InferenceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inferences.
func (c *FakeInferences) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(inferencesResource, c.ns, opts))

}

// Create takes the representation of a inference and creates it.  Returns the server's representation of the inference, and an error, if there is any.
func (c *FakeInferences) Create(ctx context.Context, inference *v2alpha1.Inference, opts v1.CreateOptions) (result *v2alpha1.Inference, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(inferencesResource, c.ns, inference), &v2alpha1.Inference{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.Inference), err
}

// Update takes the representation of a inference and updates it. Returns the server's representation of the inference, and an error, if there is any.
func (c *FakeInferences) Update(ctx context.Context, inference *v2alpha1.Inference, opts v1.UpdateOptions) (result *v2alpha1.Inference, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(inferencesResource, c.ns, inference), &v2alpha1.Inference{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.Inference), err
}

// Delete takes name of the inference and deletes it. Returns an error if one occurs.
func (c *FakeInferences) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(inferencesResource, c.ns, name, opts), &v2alpha1.Inference{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInferences) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(inferencesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2alpha1.InferenceList{})
	return err
}

// Patch applies the patch and returns the patched inference.
func (c *FakeInferences) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.Inference, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inferencesResource, c.ns, name, pt, data, subresources...), &v2alpha1.Inference{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2alpha1.Inference), err
}
