/*
Copyright 2019-2023 TensorChord Inc.

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/tensorchord/openmodelz/modelzetes/pkg/client/clientset/versioned/typed/modelzetes/v2alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTensorchordV2alpha1 struct {
	*testing.Fake
}

func (c *FakeTensorchordV2alpha1) Inferences(namespace string) v2alpha1.InferenceInterface {
	return &FakeInferences{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTensorchordV2alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
