/*
Copyright 2023 TensorChord Inc.

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/tensorchord/openmodelz/ingress-operator/pkg/client/clientset/versioned/typed/modelzetes/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTensorchordV1 struct {
	*testing.Fake
}

func (c *FakeTensorchordV1) InferenceIngresses(namespace string) v1.InferenceIngressInterface {
	return &FakeInferenceIngresses{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTensorchordV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
