/*
Copyright 2019-2023 TensorChord Inc.

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

// InferenceListerExpansion allows custom methods to be added to
// InferenceLister.
type InferenceListerExpansion interface{}

// InferenceNamespaceListerExpansion allows custom methods to be added to
// InferenceNamespaceLister.
type InferenceNamespaceListerExpansion interface{}
