---
apiVersion: v1
kind: Service
metadata:
  name: agent-provider
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
  labels:
    app: {{ template "openmodelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: agent
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  selector:
    app: agent
