{{- $providerReadTimeout :=  default .Values.agent.readTimeout .Values.modelzetes.readTimeout }}
{{- $providerWriteTimeout :=  default .Values.agent.writeTimeout .Values.modelzetes.writeTimeout }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "openmodelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: agent
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: agent
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.agent.replicas }}
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
      labels:
        app: agent
    spec:
      priorityClassName: {{ .Values.priorityClass.modelz }}
      serviceAccountName: {{ .Release.Name }}-operator
      {{- if .Values.basicAuth }}
      - name: auth
        secret:
          secretName: basic-auth
      {{- end }}
      {{- if .Values.privatedImage }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
      - name: agent
        resources:
          {{- .Values.agent.resources | toYaml | nindent 12 }}
        image: {{ .Values.agent.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
          - /usr/bin/agent
          {{- if .Values.debug }}
          - --debug
          - --dev
          {{- end }}
        {{- if .Values.securityContext }}
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10001
        {{- end }}
        livenessProbe:
          {{- if $.Values.agent.livenessProbe }}
          initialDelaySeconds: {{ $.Values.agent.livenessProbe.initialDelaySeconds | default 0 }}
          periodSeconds: {{ $.Values.agent.livenessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ $.Values.agent.livenessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ $.Values.agent.livenessProbe.failureThreshold | default 3 }}
          successThreshold: {{ $.Values.agent.livenessProbe.successThreshold | default 1 }}
          {{- end }}
          {{- if .Values.httpProbe }}
          httpGet:
            path: /healthz
            port: 8080
          {{- else }}
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=5
            - --spider
            - http://localhost:8080/healthz
          {{- end }}
        readinessProbe:
          {{- if $.Values.agent.readinessProbe }}
          initialDelaySeconds: {{ $.Values.agent.readinessProbe.initialDelaySeconds | default 0 }}
          periodSeconds: {{ $.Values.agent.readinessProbe.periodSeconds | default 10 }}
          timeoutSeconds: {{ $.Values.agent.readinessProbe.timeoutSeconds | default 5 }}
          failureThreshold: {{ $.Values.agent.readinessProbe.failureThreshold | default 3 }}
          successThreshold: {{ $.Values.agent.readinessProbe.successThreshold | default 1 }}
          {{- end }}
          {{- if .Values.httpProbe }}
          httpGet:
            path: /healthz
            port: 8080
          {{- else }}
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=5
            - --spider
            - http://localhost:8080/healthz
          {{- end }}
        env:
        - name: MODELZ_AGENT_SERVER_PORT
          value: "8080"
        - name: MODELZ_AGENT_SERVER_READ_TIMEOUT
          value: "{{ .Values.agent.readTimeout }}"
        - name: MODELZ_AGENT_SERVER_WRITE_TIMEOUT
          value: "{{ .Values.agent.writeTimeout }}"
        - name: MODELZ_AGENT_METRICS_PROMETHEUS_PORT
          value: "9090"
        - name: MODELZ_AGENT_METRICS_PROMETHEUS_HOST
          value: "prometheus.{{ .Release.Namespace }}"
        - name: MODELZ_AGENT_EVENT_ENABLED
          value: "false"
        - name: MODELZ_AGENT_INGRESS_ENABLED
          value: "false"
        {{- if .Values.basicAuth }}
        - name: basic_auth
          value: "true"
        - name: secret_mount_path
          value: "/var/secrets"
        {{- end }}
        volumeMounts:
        {{- if .Values.basicAuth }}
        - name: auth
          readOnly: true
          mountPath: "/var/secrets"
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
