apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "openmodelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: agent
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: agent
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: agent
