apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.inference }}
value: {{ .Values.priorityClass.inferenceValue }}
globalDefault: false
description: "This priority class should be used for inference pods only."
