{{- if .Values.generateBasicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "openmodelz.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: agent
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  basic-auth-user: {{ "admin" | b64enc | quote }}
  basic-auth-password: {{ randAlphaNum 12 | b64enc | quote }}
{{- end }}
