/*
Copyright 2023 TensorChord Inc.

Licensed under the MIT license. See LICENSE file in the project root for full license information.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/tensorchord/openmodelz/ingress-operator/pkg/apis/modelzetes/v1"
	"github.com/tensorchord/openmodelz/ingress-operator/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type TensorchordV1Interface interface {
	RESTClient() rest.Interface
	InferenceIngressesGetter
}

// TensorchordV1Client is used to interact with features provided by the tensorchord.ai group.
type TensorchordV1Client struct {
	restClient rest.Interface
}

func (c *TensorchordV1Client) InferenceIngresses(namespace string) InferenceIngressInterface {
	return newInferenceIngresses(c, namespace)
}

// NewForConfig creates a new TensorchordV1Client for the given config.
func NewForConfig(c *rest.Config) (*TensorchordV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &TensorchordV1Client{client}, nil
}

// NewForConfigOrDie creates a new TensorchordV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *TensorchordV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new TensorchordV1Client for the given RESTClient.
func New(c rest.Interface) *TensorchordV1Client {
	return &TensorchordV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *TensorchordV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
