// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package query

import (
	"database/sql"

	"github.com/google/uuid"
)

type DeploymentEvent struct {
	ID           uuid.UUID      `json:"id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UserID       uuid.NullUUID  `json:"user_id"`
	DeploymentID uuid.NullUUID  `json:"deployment_id"`
	Message      sql.NullString `json:"message"`
	EventType    sql.NullString `json:"event_type"`
}
