// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package query

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDeploymentEvent(ctx context.Context, arg CreateDeploymentEventParams) (DeploymentEvent, error)
	ListDeploymentEvents(ctx context.Context, arg ListDeploymentEventsParams) ([]DeploymentEvent, error)
	ListUserEvents(ctx context.Context, userID uuid.NullUUID) ([]DeploymentEvent, error)
}

var _ Querier = (*Queries)(nil)
