name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '**.go'
      - '**/Makefile'
      - 'go.**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '**.go'
      - '**/Makefile'
      - 'go.**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typos-check:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3
      - name: Check spelling with custom config file
        uses: crate-ci/typos@v1.16.2
        with:
          config: ./typos.toml

  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest]
        dir: ["modelzetes", "autoscaler", "agent", "mdz"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: test
        run: |
          cd ${{ matrix.dir }}
          make
          make test
          make fmt
          git diff --exit-code || (echo 'Please run "make fmt" to format code' && exit 1);
